### ISSUE TITLE
Create component for texts

### ISSUE THREAD

**Issue by amje** [yandex-cloud/uikit#128]
Proposal:
 ```jsx
 <Text variant="display-1" tag="h1" className="title">
    My Text
</Text>
 ```

**Comment by IsaevAlexandr** [comment]
Hi, i think that there should also be a prop about the color of the text for convenience from main palette from [here](https://preview.yandexcloud.dev/uikit/?path=/story/colors--texts) 
![image](https://user-images.githubusercontent.com/27916444/163322420-cfbf138b-62b2-4580-98c5-2a431f1e74d9.png)
```tsx
<Text variant="display-1" tag="h1" className="title" color="secondary">
   My Text
</Text>
```
--- 
in addition, in my opinion, it is possible to make a more convenient api for developers with access to quick documentation via `jsdoc` by hovering over a  component property:
<img width="841" alt="image" src="https://user-images.githubusercontent.com/27916444/163325146-49d6af63-6f97-48fa-8fcd-677b83f623a0.png">
<img width="880" alt="image" src="https://user-images.githubusercontent.com/27916444/163325228-ca0a8cb4-f903-4b3a-9174-ceb3815367e1.png">

if you don't mind I can do a pr with a more detailed proposal

**Comment by IsaevAlexandr** [comment]
Hi!I think this component should also there is an opportunity to set the color from the Main palette from [here](https://preview.yandexcloud.dev/uikit/?path=/story/colors--texts)
```jsx
<Text variant="display-1" tag="h1" className="title" color="primary">
   My Text
</Text>
```
---

in addition, in my opinion, it is possible to make a more convenient api for developers with access to quick documentation via jsdoc by hovering over a property (the names are terrible in this example, but I think the meaning is clear)

![image](https://user-images.githubusercontent.com/27916444/163325731-32eaf549-e801-4ece-9fb0-7e6e94ca9f31.png)

<img width="771" alt="image" src="https://user-images.githubusercontent.com/27916444/163325695-9618e610-6680-4469-a33d-b67a0eb475eb.png">




if you don't mind I can do a pr with a more detailed proposal

**Comment by amje** [comment]
> Hi!I think this component should also there is an opportunity to set the color from the Main palette from [here](https://preview.yandexcloud.dev/uikit/?path=/story/colors--texts)
> 
> ```js
> <Text variant="display-1" tag="h1" className="title" color="primary">
>    My Text
> </Text>
> ```
> 
> in addition, in my opinion, it is possible to make cleaner syntax and more convenient api for developers with access to quick documentation via jsdoc by hovering over a property (the names are terrible in this example, but I think the meaning is clear)
> 
> ![image](https://user-images.githubusercontent.com/27916444/163325731-32eaf549-e801-4ece-9fb0-7e6e94ca9f31.png)
> 
> <img alt="image" width="771" src="https://user-images.githubusercontent.com/27916444/163325695-9618e610-6680-4469-a33d-b67a0eb475eb.png">
> 
> if you don't mind I can do a pr with a more detailed proposal

LGTM!

**Comment by ogonkov** [comment]
What about having it as a hook?

```
const textClassName = useText({
  variant: 'display-1',
});

<div className={textClassName}/>
```

**Comment by IsaevAlexandr** [comment]
> What about having it as a hook?
> 
> ```js
> const textClassName = useText({
>   variant: 'display-1',
> });
> 
> <div className={textClassName}/>
> ```

a hook is a way to give some kind of state to an entity. Match easy to get predefined styles like it's done in css modules
```jsx
import {text} from 'uikit`
...
<div className={text.display1}>some text</div>
```
But the problem is what you want to use all design system abilities. In this way it's will be hard to manage all parts like `colors` and `spaces`. You have to use some 3-d party packeges to handle this:
```jsx
import {text, color, space} from 'uikit`
import clsx from 'clsx`
...
<div className={clsx(text.display1, color.primary, space.mr2)}>some text</div>
```

It is much easier to use components that everyone knows about the design system and know how to work with it

**Comment by amje** [comment]
> Hi! There is #141 my suggestion about the component

Awesome. I'll check it soon
