### ISSUE TITLE
Попытался заюзать пакет в проекте next.js - не получилось

### ISSUE THREAD

**Issue by niktverd** [yandex-cloud/uikit#261]
<img width="765" alt="Screenshot 2022-07-23 at 13 30 20" src="https://user-images.githubusercontent.com/61203447/180595349-08200c46-74ac-48e5-8c71-161aa606e86b.png">

**Comment by ogonkov** [comment]
Try this tip https://github.com/yandex-cloud/uikit/issues/200#issuecomment-1169882876
