### ISSUE TITLE
Inline style for Skeleton

### ISSUE THREAD

**Issue by ierehon1905** [yandex-cloud/uikit#96]
https://github.com/yandex-cloud/uikit/blob/da9f256ac9fa521fe616bfa2b1d013068db74a2a/src/components/Skeleton/Skeleton.tsx#L8-L10

Hi, I would like to use skeleton to show preload and I wondered if it could be passed `styles` prop directly, or maybe width/height props. It seems tiresome to create new classes for each element to stub.

Or maybe there are some best practices on how to use this skeleton

**Comment by amje** [comment]
@ierehon1905  Hi! It seems legit. Can you send PR?
